name: Sample React CI Pipeline/Workflow

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Check node version
        run: node -v

      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: List directories
        run: ls

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Run build
        run: npm run build

      - name: Upload product-ready build files # uploading the build files as artifacts so that they can be used in the deployment step , we are uploading the dist folder as that is where the build files are generated
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
